stages:
  - build
  - deploy

build-client:
  stage: build
  image: node:latest
  script:
    - cd client && yarn install
    - yarn build
  artifacts:
    expire_in: 7 days
    paths:
      - ./client/build/

deploy-to-dev:
  stage: deploy
  image: node:latest
  before_script:
    - npm config set prefix /usr/local
    - npm install -g serverless
    - cd backend && npm install
  script:
    - sls deploy
    

deploy-client-dev:
  stage: deploy
  variables:
    AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
  image: registry.gitlab.com/gitlab-org/cloud-deploy:latest
  script:
      - aws s3 cp --recursive ./client/build s3://chatbot-static-ose