service:
  name: chatbot
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'eu-north-1'}

functions:
  getAirports:
    handler: http/getAirports.handler
    events:
      - http:
          method: get
          path: airports
          cors: true
  getFlights:
    handler: http/getFlights.handler
    events:
      - http:
          method: get
          path: flights
          cors: true
